#! /bin/bash

function runDebugModeForClassLoading {
	# For classloading
	mx Rscript --J @'-DR:+IgnoreVisibility -G:-TruffleOSR -G:-TruffleBackgroundCompilation -G:+TraceTruffleCompilation -XX:+TraceClassLoading -XX:+TraceClassUnloading -XX:-UseJVMCIClassLoader' $* 
}

. source.sh

mx Rscript --J @'-DR:+IgnoreVisibility 
-G:-TruffleOSR 
-G:-TruffleBackgroundCompilation 
-G:-TraceTruffleCompilation  
-XX:-UseJVMCIClassLoader 
-Dmarawacc.printOCLKernel=true
-Dmarawacc.printOCLInfo=true
-Dmarawacc.dumpGraph=false 
-Dastx.marawacc.profiler=true  
-Dastx.marawacc.optimizeRSequence=true 
-Dastx.marawacc.primArrays=true ' $* 

