#! /bin/bash
mx Rscript --J @'-DR:+IgnoreVisibility -G:-TruffleOSR -G:-TruffleBackgroundCompilation -G:+TraceTruffleCompilation -G:Dump=:1 -G:MethodFilter=Truffle.* -XX:-UseJVMCIClassLoader -Dmarawacc.dumpGraph=true ' $*

