./run benchmarks/fastR/saxpy/saxpyGPU.R 10000 
./run benchmarks/fastR/blackscholes/blackscholesGPU.R 1000
./run benchmarks/fastR/montecarlo/montecarloGPU.R 100
./run benchmarks/fastR/kmeans/kmeansGPU.R 10000
./run benchmarks/fastR/nbody/nbodyGPU.R 100
./run benchmarks/fastR/dft/dftGPU.R 100
./run benchmarks/fastR/spectralNorm/spectralNormGPU.R 100
./run benchmarks/fastR/pi/piGPU.R 1000
./run benchmarks/fastR/euler/eulerGPU.R 100
./run benchmarks/fastR/mandelbrot/mandelbrotGPU.R 100
