#! /bin/bash

# High Performance Execution
mx Rscript --J @'-DR:+IgnoreVisibility 
-G:-TruffleOSR 
-G:-TruffleBackgroundCompilation 
-G:-TraceTruffleCompilation  
-XX:-UseJVMCIClassLoader 
-Dmarawacc.printOCLInfo=false
-Dmarawacc.dumpGraph=false 
-Dastx.marawacc.profiler=true 
-Xmx12g -Xms12g 
-XX:+UseSerialGC 
-Dmarawacc.printOCLKernel=false 
-Dastx.marawacc.optimizeRSequence=true  
-Dastx.marawacc.primArrays=true ' $* 
 
