#! /bin/bash

# High Performance Execution
mx Rscript --J @'-DR:+IgnoreVisibility 
-G:-TruffleOSR 
-G:-TruffleBackgroundCompilation 
-G:-TraceTruffleCompilation  
-XX:-UseJVMCIClassLoader 
-Dmarawacc.printOCLInfo=false
-Dmarawacc.dumpGraph=false 
-Dastx.marawacc.profiler=true
-Dmarawacc.multidevice=false 
-Xmx16g -Xms16g 
-XX:+UseSerialGC 
-Dmarawacc.printOCLKernel=true 
-Dastx.marawacc.optimizeRSequence=true  
-Dastx.marawacc.primArrays=true ' $* 
 
